### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by randiyasen** [viraj-bookanna/aplusewings#1]
thanks

**Comment by viraj-bookanna** [comment]
> App returns to login screen when video id pasted. I found that the heroku hosted applications on https://github.com/viraj-bookanna/aplusewings/blob/main/app/src/main/java/lk/live/aplusewings/vars.java not working.

Yeah the app is discontinued and now we use web version.
Join https://t.me/SmartEducationSoIutions for updates
